# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9.10"
        installer:
          - pyenv

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: gabrielfalcao/pyenv-action@v9
        with:
          default: "${{ matrix.python }}"

      - run: ./runtest.sh test/test_functions.sh --filter "${{ matrix.installer }}"

  macos:
    # The type of runner that the job will run on
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.9.10"
        installer:
          - pyenv
          - homebrew

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: brew install pyenv
        if: matrix.installer == 'pyenv'

      - run: pyenv install "${{ matrix.python }}"
        if: matrix.installer == 'pyenv'

      - run: ./runtest.sh test/test_functions.sh --filter "${{ matrix.installer }}"
        env:
          BATS_MOCK_HOMEBREW: 0
          BATS_MOCK_PYENV: 0
