name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-pyenv:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - { test_shell: "ash" }
          - { test_shell: "bash" }
          - { test_shell: "dash" }
          - { test_shell: "ksh" }
          - { test_shell: "zsh" }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install shell
        run: sudo apt-get install "${{ matrix.test_shell }}"

      - name: Choose shell
        run: |
          echo 'TEST_SHELL=${{ matrix.test_shell }}' >> $GITHUB_ENV
          command -v ${{ matrix.test_shell }}

      - uses: gabrielfalcao/pyenv-action@v14
        with:
          default: "3.9.13"

      - name: Test functions with pyenv
        run: ./runtest.sh test/test_functions.sh --filter-tags vendor:pyenv

      - name: Test commands
        run: ./runtest.sh test/test_commands.sh

  macos-homebrew:
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.9.13"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test functions with homebrew
        run: ./runtest.sh test/test_functions.sh --filter-tags vendor:homebrew
        env:
          BATS_MOCK_HOMEBREW: 0

      - name: Test commands
        run: ./runtest.sh test/test_commands.sh

  macos-pyenv:
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.9.13"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install pyenv
        run: brew install pyenv

      - name: Install Python ${{ matrix.python }} with pyenv
        run: pyenv install "${{ matrix.python }}"

      - name: Test functions with pyenv
        run: ./runtest.sh test/test_functions.sh --filter-tags vendor:pyenv
        env:
          BATS_MOCK_PYENV: 0

      - name: Test commands
        run: ./runtest.sh test/test_commands.sh

  macos-uv:
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.12.3"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up uv
        # Install latest uv version using the installer
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Python ${{ matrix.python }} with uv
        run: uv python install "${{ matrix.python }}"

      - name: Test functions with uv
        run: ./runtest.sh test/test_functions.sh --filter-tags vendor:uv

      - name: Test commands
        run: ./runtest.sh test/test_commands.sh
