name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9.10"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: gabrielfalcao/pyenv-action@v9
        with:
          default: "${{ matrix.python }}"

      # Test functions with pyenv
      - run: ./runtest.sh test/test_functions.sh --filter "pyenv"

      # Test commands
      - run: ./runtest.sh test/test_commands.sh

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.9.10"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Test functions with homebrew alone (pyenv is not installed at this point)
      - run: ./runtest.sh test/test_functions.sh --filter "homebrew"
        env:
          BATS_MOCK_HOMEBREW: 0

      # Test functions with pyenv (both homebrew and pyenv are installed at this point)
      - run: brew install pyenv
      - run: pyenv install "${{ matrix.python }}"

      - run: ./runtest.sh test/test_functions.sh --filter "pyenv"
        env:
          BATS_MOCK_PYENV: 0

      # Test commands
      - run: ./runtest.sh test/test_commands.sh
