name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9.10"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: gabrielfalcao/pyenv-action@v9
        with:
          default: "${{ matrix.python }}"

      - name: Show bash version
        run: bash --version

      - name: Test functions with pyenv
        run: ./runtest.sh test/test_functions.sh --filter "PYENV"

      - name: Test commands
        run: ./runtest.sh test/test_commands.sh

  macos-homebrew:
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.9.10"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Show bash version
        run: bash --version

      - name: Test functions with homebrew
        run: ./runtest.sh test/test_functions.sh --filter "HOMEBREW"
        env:
          BATS_MOCK_HOMEBREW: 0

      - name: Test commands
        run: ./runtest.sh test/test_commands.sh

  macos-pyenv:
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.9.10"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install pyenv
        run: brew install pyenv

      - name: Install Python ${{ matrix.python }} with pyenv
        run: pyenv install "${{ matrix.python }}"

      - name: Test functions with pyenv
        run: ./runtest.sh test/test_functions.sh --filter "PYENV"
        env:
          BATS_MOCK_PYENV: 0

      - name: Test commands
        run: ./runtest.sh test/test_commands.sh
